---
abstract: 'Dynamic DNS client for CloudFlare'
author:
  - 'Peter Roberts <me+dev@peter-r.co.uk>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-DDFlare
no_index:
  directory:
    - t
    - inc
requires:
  Getopt::Long: 2.39
  Net::DNS::CloudFlare::DDNS: 0.03
  Pod::Usage: 1.61
  Readonly: 1.03
  YAML::Any: 0.77
  perl: 0
version: 0.08
